-- local function get_safe_hash(data)
--   if not data then
--     return ''
--   end
--   return vim.fn.sha256(data)
-- end
-- -- 4. Execute Compiledb (Using vim.system + Muting)
-- function M.run_compiledb()
--   if is_ignoring_watcher then
--     return
--   end
--   is_ignoring_watcher = true -- Mute watcher
--
--   vim.notify('Generating Compilation DB...', vim.log.levels.INFO, { title = 'PlatformIO' })
--
--   vim.system({ 'pio', 'run', '-t', 'compiledb' }, { text = true }, function(obj)
--     vim.schedule(function()
--       is_ignoring_watcher = false -- Unmute
--       if obj.code == 0 then
--         vim.notify('Compiledb updated', vim.log.levels.INFO, { title = 'PlatformIO' })
--         -- Manual refresh once finished
--         pio_manager.refresh(function()
--           -- boilerplate_gen([[.clangd]], vim.g.platformioRootDir)
--           -- boilerplate_gen([[.clangd]], _G.metadata.core_dir) --require('platformio.utils.pio').get_pio_dir('core')) --vim.env.PLATFORMIO_CORE_DIR)
--           -- pio_generate_db()
--           lsp.lsp_restart('clangd')
--         end)
--       else
--         vim.notify('Compiledb failed: ' .. (obj.stderr or 'Unknown error'), vim.log.levels.ERROR)
--       end
--     end)
--   end)
-- end
--
-- -- 5. Bulletproof Watcher (Content-aware & Lock-aware)
-- function M.start_pio_watcher()
--   local dir_path = vim.uv.cwd()
--   local ini_path = dir_path .. '/platformio.ini'
--   if not dir_path or vim.fn.filereadable(ini_path) == 0 then
--     return
--   end
--
--   -- Seed the initial hash
--   local init_f = io.open(ini_path, 'r')
--   if init_f then
--     last_ini_hash = get_safe_hash(init_f:read('*a'))
--     init_f:close()
--   end
--
--   local handle = vim.uv.new_fs_event()
--   if not handle then
--     return
--   end
--
--   handle:start(
--     dir_path,
--     { recursive = false },
--     vim.schedule_wrap(function(err, filename)
--       if err or is_ignoring_watcher or filename ~= 'platformio.ini' then
--         return
--       end
--
--       -- Safe read (pcall handles Windows file locks during build)
--       local ok, content = pcall(function()
--         local f = io.open(ini_path, 'r')
--         if not f then
--           return nil
--         end
--         local data = f:read('*a')
--         f:close()
--         return data
--       end)
--
--       if ok and content then
--         local new_hash = get_safe_hash(content)
--         if new_hash ~= last_ini_hash then
--           last_ini_hash = new_hash
--           -- Trigger refresh via your manager
--           pio_manager.refresh(function()
--             boilerplate_gen([[.clangd]], vim.g.platformioRootDir)
--             boilerplate_gen([[.clangd]], _G.metadata.core_dir) --require('platformio.utils.pio').get_pio_dir('core')) --vim.env.PLATFORMIO_CORE_DIR)
--             -- pio_generate_db()
--             M.run_compiledb()
--             lsp.lsp_restart('clangd')
--           end)
--         end
--       end
--     end)
--   )
-- end
